### ISSUE TITLE
`convert_mobv2_xnnpack_int8.py` crashes on torch 2.11+ when torchao 0.15 is installed — no version constraints documented

### ISSUE THREAD

**Issue by xyf5432** [Mjrovai/EdgeML-with-Raspberry-Pi#2]
## Summary

[`EXECUTORCH/scripts/convert_mobv2_xnnpack_int8.py:8-10`](https://github.com/Mjrovai/EdgeML-with-Raspberry-Pi/blob/main/EXECUTORCH/scripts/convert_mobv2_xnnpack_int8.py) imports at module level:

```python
from torchao.quantization.pt2e.quantize_pt2e import (
    prepare_pt2e,
    convert_pt2e,
)
```

On **torch 2.11+ with torchao 0.15 installed**, this import crashes immediately:

```
AttributeError: module 'torch.ao.quantization' has no attribute 'quantizer'. Did you mean: 'quantize'?
```

Cause: torchao 0.15.0's `torchao/quantization/pt2e/quantize_pt2e.py:44` still has a
function-signature annotation `torch.ao.quantization.quantizer.quantizer.Quantizer`,
which Python evaluates at import time. torch 2.11 removed that module, so the import
fails even though the script itself never touches the old path. torchao 0.16.0 removed
the stale annotation — the script works fine with torchao>=0.16 on any torch version.

torch 2.9.x + torchao 0.15 (the versions this script was written against) is unaffected.

## Why it happens to users

The repo documents no pinned environment. `EXECUTORCH/README.md` tells readers to run
`pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu`
and `pip install executorch` — no version constraints, and **no torchao install step
at all**. Notably, the PyPI `executorch` package does not declare `torchao` in its
dependencies ([setup.py `_base_dependencies()`](https://github.com/pytorch/executorch/blob/main/setup.py#L178-L201):
"consumers bring their own"), so `torchao` is whatever the reader's environment
happens to have. Consequences on a recent torch (2.11+):

- no torchao installed → `ModuleNotFoundError: No module named 'torchao'`
- torchao 0.15.x present (e.g. from an older project) → the `AttributeError`
  above; pip never upgrades it because nothing declares `torchao>=0.16`
- torchao 0.16+ → works fine

## Suggested fix

Document a minimum torchao version, e.g. in the README / a `requirements.txt`:

```
torchao>=0.16
```

(or pin `torch<2.11` as an alternative). That single line makes pip upgrade a
stale 0.15 and the script works unchanged.

## References

- torchao 0.15.0 bug: [quantize_pt2e.py:44](https://github.com/pytorch/ao/blob/v0.15.0/torchao/quantization/pt2e/quantize_pt2e.py#L44) (removed in 0.16.0)
- executorch dependencies (no torchao): [setup.py](https://github.com/pytorch/executorch/blob/main/setup.py#L171-L201)
- PyTorch migration plan: [Torch.ao.quantization Migration Plan](https://dev-discuss.pytorch.org/t/torch-ao-quantization-migration-plan/2810)
